version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest-cuda
    container_name: rag_ollama_cuda
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_network

volumes:
  ollama_data:

networks:
  rag_network:
    name: ollama-rag_rag_network
