services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: rag_backend
    environment:
      - OLLAMA_BASE_URL=http://172.17.0.1:11434
    networks:
      - rag_network

  caddy:
    build:
      context: .
      dockerfile: docker/caddy.Dockerfile
    container_name: rag_caddy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019" # Admin API
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/srv/static:ro
      - ./templates:/srv/templates:ro
      - ./assets:/srv/assets:ro
    environment:
      - DOMAIN=home.freundcloud.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  ollama_data:
  caddy_data:
  caddy_config:
